---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ruby_backend]
    attributes:
      ruby_backend:
        deploy_user: 'deploy'
        deploy_ssh_keys:
          - 'ssh-rsa test-pubkey'
          - 'ssh-rsa test-pubkey2'
        application_name: 'test_app'
        db_settings:
          adapter: postgresql
          username: test_user
          password: password
          database: test_database
          host: host
        configure_thin: true